---
hostname: v4
domain: paleblue.systems
action: sync
provider: shock-dedicated
dns:
  alias:
    -
      name: ws.paleblue.systems
package:
  - certbot
  - dirmngr
  - nginx
  - rsync
  - scanlogd
  - sqlite3
  - unattended-upgrades
  - unzip
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJx8I0j6oYirfie4pAQZQB1+fWJ7w5mFZayQvLhtSV0
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfxkCWHMdmXufF7hLHGyQdV+v64NTbEiUFDhxyi6+fX
      users:
        - dengjianping
        - stechu
        - ferrell-code
        - garandor
        - ghzlatarev
        - zqhxuyuan
command:
  - sudo passwd -l root
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - systemctl is-active nginx-prometheus-exporter.service || sudo systemctl restart nginx-prometheus-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - '(test -s /etc/letsencrypt/renewal/$(hostname -f).conf && grep webroot_path /etc/letsencrypt/renewal/$(hostname -f).conf) || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/nginx-prometheus-exporter || ( curl -sLo /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && sudo tar xvfz /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz -C /usr/local/bin nginx-prometheus-exporter )
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.6.1/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
file:
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/promtail.service
    target: /etc/systemd/system/promtail.service
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/promtail/promtail.yml
    target: /etc/promtail/promtail.yml
    sha256: 8c70b3b76053d7897e54b75d046541d8aeee7ffdddb6c88831737af8e374ab35
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/prometheus-node-exporter.service
    target: /etc/systemd/system/prometheus-node-exporter.service
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/nginx-prometheus-exporter.service
    target: /etc/systemd/system/nginx-prometheus-exporter.service
    command:
      pre:
        - systemctl is-active --quiet nginx-prometheus-exporter.service && sudo systemctl stop nginx-prometheus-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now nginx-prometheus-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/certbot.conf
    target: /etc/nginx/sites-available/certbot.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/certbot.conf /etc/nginx/sites-enabled/certbot.conf
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/status.conf
    target: /etc/nginx/sites-available/status.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
        - sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/paleblue.systems/v4/etc/nginx/sites-available/polkadot.conf
    target: /etc/nginx/sites-available/polkadot.conf
    sha256: b69627b010092081945ef03b0016fdcfc3676c02298c33220acab9fb6a29abf0
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/polkadot.conf /etc/nginx/sites-enabled/polkadot.conf
        - sudo systemctl stop nginx.service
        - sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/ws.paleblue.systems.conf
    target: /etc/nginx/sites-available/ws.paleblue.systems.conf
    sha256: c4a52067731b706d06ff7b92af1a18bcdf4cf251f8cca3594fd172727ba7baf5
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.paleblue.systems.conf /etc/nginx/sites-enabled/ws.paleblue.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/ws.archive.paleblue.systems.conf
    target: /etc/nginx/sites-available/ws.archive.paleblue.systems.conf
    sha256: 83b9a9a50dfd37482e5ba695b397ef81c27e036336c6cced19c0ca54e848154e
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.archive.paleblue.systems.conf /etc/nginx/sites-enabled/ws.archive.paleblue.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
