---
hostname: c2
domain: manta.systems
action: sync
provider: shock-dedicated
dns:
  alias:
    -
      name: ws.manta.systems
      weight: 200
    -
      name: ws.archive.manta.systems
      weight: 200
package:
  - auditd
  - certbot
  - dirmngr
  - nginx
  - python3-certbot-nginx
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
      users:
        - stechu
command:
  - sudo passwd -l root
  - systemctl is-active manta.service || sudo systemctl restart manta.service
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/go-audit || ( curl -sLo /tmp/go-audit-linux-amd64.tar.gz https://github.com/slackhq/go-audit/releases/download/v1.1.1/go-audit-linux-amd64.tar.gz && sudo tar xvfz /tmp/go-audit-linux-amd64.tar.gz -C /usr/local/bin )
  - test -x /usr/bin/unzip || sudo apt-get install -y unzip
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.6.1/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
file:
  -
    source: https://gist.githubusercontent.com/grenade/74b5da418ac15b3c9679c1ec6b16f821/raw/promtail.service
    target: /etc/systemd/system/promtail.service
    sha256: 35ab9c5313c3729bf7cdedde972cf7b6e566d75bc5789edd88ab034a4e14096a
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://gist.githubusercontent.com/grenade/74b5da418ac15b3c9679c1ec6b16f821/raw/promtail.yml
    target: /etc/promtail/promtail.yml
    sha256: 7d012c53e91df1c741ed9d5763b91cbb68e82385a1556057c24966ec4634f7ae
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: 'https://gist.githubusercontent.com/grenade/cc6f567219f328f0aa468b4744230ffe/raw/prometheus-node-exporter.service'
    target: /etc/systemd/system/prometheus-node-exporter.service
    sha256: 4e551485c07fb89f348fd154f264a52cded39e87b6b8f8aad9115b1d353ede05
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
