[indexer.configuration]
frequency = 2
rpc_method = "mantaPay_pull_ledger_diff"
full_node = "ws://127.0.0.1:9944"
port = 7788
prometheus_port = 7789

[server.configuration]
max_request_body_size = 10
max_response_body_size = 10
max_connections = 1000
max_subscriptions_per_connection = 1024
max_log_length = 4096
batch_requests_supported = true
ping_interval = 30

[db.configuration]
db_path = "utxo.db"
pool_size = 16
