---
hostname: a4
domain: calamari.systems
ip: 45.155.39.202
action: sync
launch: '2022-09-08T11:21:00Z'
provider: shock-dedicated
price:
  amount: 170.98
  currency: usd
  term: quarterly
dns:
  alias:
    -
      name: ws.calamari.systems
      weight: 25
    -
      name: ws.archive.calamari.systems
      weight: 200
package:
  - auditd
  - certbot
  - nginx
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      users:
        - manta-ops
        - stechu
command:
  - sudo passwd -l root
  - systemctl is-active calamari.service || sudo systemctl start calamari.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf || sudo certbot certonly --expand -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/go-audit || ( curl -sLo /tmp/go-audit-linux-amd64.tar.gz https://github.com/slackhq/go-audit/releases/download/v1.1.1/go-audit-linux-amd64.tar.gz && sudo tar xvfz /tmp/go-audit-linux-amd64.tar.gz -C /usr/local/bin )
file:
  -
    source: 'https://gist.githubusercontent.com/grenade/cc6f567219f328f0aa468b4744230ffe/raw/prometheus-node-exporter.service'
    target: /etc/systemd/system/prometheus-node-exporter.service
    sha256: 4e551485c07fb89f348fd154f264a52cded39e87b6b8f8aad9115b1d353ede05
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
  -
    source: 'https://github.com/Manta-Network/Manta/releases/download/v3.4.0/manta'
    target: /usr/bin/manta
    sha256: 09001214fd9b95f6671f0ab121c4e7d2982ba51625038bca90712b49a1ddddac
    command:
      pre:
        - systemctl is-active --quiet calamari.service && sudo systemctl stop calamari.service
      post:
        - sudo chmod +x /usr/bin/manta
        - sudo ln -sfr /usr/bin/manta /usr/bin/calamari
        - systemctl is-active --quiet calamari.service || sudo systemctl start calamari.service
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/Manta/manta/genesis/calamari-genesis.json'
    target: /usr/share/substrate/calamari.json
    sha256: 40c9c3896cac2478e891aaec9728f94aba4ff7faa2da85b9618f5c743c34fd31
    command:
      pre:
        - test -d /usr/share/substrate || sudo mkdir -p /usr/share/substrate
      post:
        - systemctl is-active --quiet calamari.service && sudo systemctl restart calamari.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/a4.calamari.systems.service'
    target: /usr/lib/systemd/system/calamari.service
    sha256: 86d51d423c2b11ed682160dc137caa8621278687915832ddc83dbbe0af8a2c3e
    command:
      pre:
        - systemctl is-active --quiet calamari.service && sudo systemctl stop calamari.service
      post:
        - getent passwd manta &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group manta
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet calamari.service || sudo systemctl enable calamari.service
        - sudo systemctl start calamari.service
  -
    source: 'https://gist.githubusercontent.com/grenade/ad1a4772c47a0977204edee78691fde1/raw/options-ssl-nginx.conf'
    target: /etc/letsencrypt/options-ssl-nginx.conf
    sha256: 17baec778c05571beb0cdeb0bc1c6da3596d44d1fe567e7fee0efef80a860d01
    command:
      pre:
        - test -d /etc/letsencrypt || sudo mkdir -p /etc/letsencrypt
      post:
        - sudo chmod 644 /etc/letsencrypt/options-ssl-nginx.conf
  -
    source: 'https://gist.githubusercontent.com/grenade/ad1a4772c47a0977204edee78691fde1/raw/ssl-dhparams.pem'
    target: /etc/letsencrypt/ssl-dhparams.pem
    sha256: 9ba6429597aeed2d8617a7705b56e96d044f64b07971659382e426675105654b
    command:
      pre:
        - test -d /etc/letsencrypt || sudo mkdir -p /etc/letsencrypt
      post:
        - sudo chmod 644 /etc/letsencrypt/ssl-dhparams.pem
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/status.conf'
    target: /etc/nginx/sites-available/status.conf
    sha256: c123caec7c2871afd3500875adb026cacffc16b7c7dde4375376d1b4fb3f1f14
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/substrate.conf'
    target: /etc/nginx/sites-available/substrate.conf
    sha256: 61d24af829cd47df256d3940f2ac5b9fe5851be3d83a8985627dadd5ff133517
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - 'sudo sed -i "s/\${fqdn}/$(hostname -f)/i" /etc/nginx/sites-available/substrate.conf'
        - sudo ln -sfr /etc/nginx/sites-available/substrate.conf /etc/nginx/sites-enabled/substrate.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/ws.calamari.systems.conf'
    target: /etc/nginx/sites-available/ws.calamari.systems.conf
    sha256: a312332c7a1945340ae033d0700c6626f6866db981e375dbd13192f1ad793c49
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.calamari.systems.conf /etc/nginx/sites-enabled/ws.calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/ws.archive.calamari.systems.conf'
    target: /etc/nginx/sites-available/ws.archive.calamari.systems.conf
    sha256: f1f2fe6f3b0aac32521a846d0fecb946e31086e366b9bdb733d428c9735af333
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.archive.calamari.systems.conf /etc/nginx/sites-enabled/ws.archive.calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
