---
hostname: a4
domain: calamari.systems
ip: 43.230.163.154
action: sync
launch: '2023-04-18T11:36:00Z'
provider: shock-dedicated
price:
  amount: 170.98
  currency: usd
  term: quarterly
dns:
  alias:
    -
      name: calamari.systems
      weight: 200
    -
      name: archive.calamari.systems
      weight: 200
    -
      name: asia.calamari.systems
      weight: 200
    -
      name: asia.archive.calamari.systems
      weight: 200
package:
  - certbot
  - dirmngr
  - nginx
  - sqlite3
  - unattended-upgrades
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJx8I0j6oYirfie4pAQZQB1+fWJ7w5mFZayQvLhtSV0
      users:
        - stechu
command:
  - sudo passwd -l root
  - systemctl is-active calamari.service || sudo systemctl restart calamari.service
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - systemctl is-active nginx-prometheus-exporter.service || sudo systemctl restart nginx-prometheus-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - '(test -s /etc/letsencrypt/renewal/$(hostname -f).conf && grep webroot_path /etc/letsencrypt/renewal/$(hostname -f).conf) || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/nginx-prometheus-exporter || ( curl -sLo /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && sudo tar xvfz /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz -C /usr/local/bin nginx-prometheus-exporter )
  - test -x /usr/bin/unzip || sudo apt-get install -y unzip
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.6.1/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
  - grep 'worker_connections 32768;' /etc/nginx/nginx.conf &> /dev/null || sudo sed -i 's/worker_connections \+[0-9]\+;/worker_connections 32768;/' /etc/nginx/nginx.conf
file:
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    target: /etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    sha256: ffff5e164772643bbc1528db9628e194b3a11058b1431d32bcfe8d31771ddaa7
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/www-data-soft-nofile.conf
    target: /etc/security/limits.d/www-data-soft-nofile.conf
    sha256: 30dc160ecfdba997dc3a02563cba4f4746fb4f7ffacdec5e8bec1a44ff1ae6dd
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/substrate-soft-nofile.conf
    target: /etc/security/limits.d/substrate-soft-nofile.conf
    sha256: 3cacb08df5fd936f2f0b6cbace43a42d72abd9cc10de7ba0d4019919833daeec
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/promtail.service
    target: /etc/systemd/system/promtail.service
    sha256: 35ab9c5313c3729bf7cdedde972cf7b6e566d75bc5789edd88ab034a4e14096a
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/promtail/promtail.yml
    target: /etc/promtail/promtail.yml
    sha256: 8c70b3b76053d7897e54b75d046541d8aeee7ffdddb6c88831737af8e374ab35
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/prometheus-node-exporter.service
    target: /etc/systemd/system/prometheus-node-exporter.service
    sha256: 4e551485c07fb89f348fd154f264a52cded39e87b6b8f8aad9115b1d353ede05
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/nginx-prometheus-exporter.service
    target: /etc/systemd/system/nginx-prometheus-exporter.service
    sha256: 551b688bbcccb24ce3eb3b977ff871242c319bdbf1a72de82b4fe4cae98cec36
    command:
      pre:
        - systemctl is-active --quiet nginx-prometheus-exporter.service && sudo systemctl stop nginx-prometheus-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now nginx-prometheus-exporter.service
  -
    source: https://github.com/Manta-Network/Manta/releases/download/v4.0.6/manta
    target: /usr/local/bin/manta
    sha256: d743b00bcafdf83560d4c409f155afd9906b56d78cd4a16926d4ded0c315afe0
    command:
      pre:
        - systemctl is-active --quiet calamari.service && sudo systemctl stop calamari.service
      post:
        - sudo chmod +x /usr/local/bin/manta
        - sudo ln -sfr /usr/local/bin/manta /usr/local/bin/calamari
        - systemctl is-active --quiet calamari.service || sudo systemctl start calamari.service
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/Manta/manta/genesis/calamari-genesis.json'
    target: /usr/share/substrate/calamari.json
    sha256: 40c9c3896cac2478e891aaec9728f94aba4ff7faa2da85b9618f5c743c34fd31
    command:
      pre:
        - test -d /usr/share/substrate || sudo mkdir -p /usr/share/substrate
      post:
        - systemctl is-active --quiet calamari.service && sudo systemctl restart calamari.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/calamari.systems/a4/etc/systemd/system/calamari.service
    target: /etc/systemd/system/calamari.service
    sha256: ea26a4163ca92ba78f6ae26fa0229ace4a9069e8a59a9a4829a697f29c5a1018
    command:
      pre:
        - systemctl is-active --quiet calamari.service && sudo systemctl stop calamari.service
      post:
        - getent passwd substrate &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group substrate
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet calamari.service || sudo systemctl enable calamari.service
        - sudo systemctl start calamari.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/status.conf
    target: /etc/nginx/sites-available/status.conf
    sha256: 03127f61971cb3cc15a278672e49182ada2506afdddb02a90cf660e82c89c3bf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
        - sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/calamari.systems/a4/etc/nginx/sites-available/calamari.conf
    target: /etc/nginx/sites-available/calamari.conf
    sha256: 3f436545d795e2079bc67e8faa2f0a8d25b64ea409f6dc105dee709638b37a3a
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/calamari.conf /etc/nginx/sites-enabled/calamari.conf
        - sudo systemctl stop nginx.service
        - sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/calamari.systems.conf
    target: /etc/nginx/sites-available/calamari.systems.conf
    sha256: cc6f52c63f06f90ed6395d3d268fc4c6b831cd9b6f9a49ee47ecb5ee715e7e1f
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/calamari.systems.conf /etc/nginx/sites-enabled/calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/archive.calamari.systems.conf
    target: /etc/nginx/sites-available/archive.calamari.systems.conf
    sha256: 8c260827b24981d7228a4dcbefd862b9c7968b295260216a45529e12fdc1b529
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/archive.calamari.systems.conf /etc/nginx/sites-enabled/archive.calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/asia.calamari.systems.conf
    target: /etc/nginx/sites-available/asia.calamari.systems.conf
    sha256: 816126932cb3718ec51c1a2f77b05aeb9af728cb7b7f75bbc09a524e7805393d
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/asia.calamari.systems.conf /etc/nginx/sites-enabled/asia.calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/asia.archive.calamari.systems.conf
    target: /etc/nginx/sites-available/asia.archive.calamari.systems.conf
    sha256: 58e5c407991d49467253ba16f8270ef34e3682e8c9f0354c24085e87e1106083
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/asia.archive.calamari.systems.conf /etc/nginx/sites-enabled/asia.archive.calamari.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/var/www/html/calamari.ico
    target: /var/www/html/calamari.ico
    sha256: 2e676c3465038990013eb1c28a035783465b587720a4deba233a6ce2d595c3e3
    command:
      pre:
        - test -d /var/www/html || sudo mkdir -p /var/www/html
      post:
        - sudo ln -sfr /var/www/html/calamari.ico /var/www/html/favicon.ico
