---
hostname: a1
domain: internal.kusama.systems
action: sync
provider: hetzner-robot
dns:
  alias:
    -
      name: ws.internal.kusama.systems
    -
      name: ws.archive.internal.kusama.systems
package:
  - auditd
  - certbot
  - dirmngr
  - nginx
  - python3-certbot-nginx
  - sqlite3
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJx8I0j6oYirfie4pAQZQB1+fWJ7w5mFZayQvLhtSV0
      users:
        - stechu
        - ferrell-code
        - garandor
        - ghzlatarev
command:
  - sudo passwd -l root
  - systemctl is-active kusama-0.service || sudo systemctl restart kusama-0.service
  - systemctl is-active kusama-1.service || sudo systemctl restart kusama-1.service
  - systemctl is-active kusama-2.service || sudo systemctl restart kusama-2.service
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/go-audit || ( curl -sLo /tmp/go-audit-linux-amd64.tar.gz https://github.com/slackhq/go-audit/releases/download/v1.1.1/go-audit-linux-amd64.tar.gz && sudo tar xvfz /tmp/go-audit-linux-amd64.tar.gz -C /usr/local/bin )
  - test -x /usr/bin/unzip || sudo apt-get install -y unzip
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.6.1/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
file:
  -
    source: https://gist.githubusercontent.com/grenade/74b5da418ac15b3c9679c1ec6b16f821/raw/promtail.service
    target: /etc/systemd/system/promtail.service
    sha256: 35ab9c5313c3729bf7cdedde972cf7b6e566d75bc5789edd88ab034a4e14096a
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://gist.githubusercontent.com/grenade/74b5da418ac15b3c9679c1ec6b16f821/raw/promtail.yml
    target: /etc/promtail/promtail.yml
    sha256: 3ad396de6e1becc80616339a413c0c1c8e21f96a3ceba2294521fac26941a52e
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: 'https://gist.githubusercontent.com/grenade/cc6f567219f328f0aa468b4744230ffe/raw/prometheus-node-exporter.service'
    target: /etc/systemd/system/prometheus-node-exporter.service
    sha256: 4e551485c07fb89f348fd154f264a52cded39e87b6b8f8aad9115b1d353ede05
    command:
      pre:
        - ( systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet prometheus-node-exporter.service || sudo systemctl enable prometheus-node-exporter.service
        - systemctl is-active --quiet prometheus-node-exporter.service || sudo systemctl start prometheus-node-exporter.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/go-audit.yml'
    target: /etc/go-audit.yml
    sha256: 8267a422d920a249b9d744a322c0824a14f2fd8acc0f88aa9caf0fae604f5ef1
    command:
      post:
        - systemctl is-active --quiet go-audit.service && sudo systemctl restart go-audit.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/go-audit.service'
    target: /etc/systemd/system/go-audit.service
    sha256: bd5536398fd1fb4b18fbbb951d86960851d47cc68a41d5bbb5ea591f9d635cf8
    command:
      pre:
        - ( systemctl is-active --quiet go-audit.service && sudo systemctl stop go-audit.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet go-audit.service || sudo systemctl enable go-audit.service
        - systemctl is-active --quiet go-audit.service || sudo systemctl start go-audit.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/usr/share/substrate/kusama-staging.json
    target: /usr/share/substrate/kusama-staging.json
    sha256: 6e0a5614a4f8a94052fd2663f153adbd34cb7794be3ac7691d8febd27c479541
    command:
      pre:
        - test -d /usr/share/substrate || sudo mkdir -p /usr/share/substrate
      post:
        - systemctl is-active --quiet kusama-0.service && sudo systemctl restart kusama-0.service
        - systemctl is-active --quiet kusama-1.service && sudo systemctl restart kusama-1.service
        - systemctl is-active --quiet kusama-2.service && sudo systemctl restart kusama-2.service
  -
    source: https://github.com/paritytech/polkadot/releases/download/v0.9.33/polkadot
    target: /usr/local/bin/polkadot
    sha256: 01b376450b958e1a74caff86bf1140220899e486baa301e5119665fc3cb37147
    command:
      pre:
        - systemctl is-active --quiet kusama-0.service && sudo systemctl stop kusama-0.service
        - systemctl is-active --quiet kusama-1.service && sudo systemctl stop kusama-1.service
        - systemctl is-active --quiet kusama-2.service && sudo systemctl stop kusama-2.service
      post:
        - sudo chmod +x /usr/local/bin/polkadot
        - sudo ln -sfr /usr/local/bin/polkadot /usr/local/bin/kusama
        - systemctl is-active --quiet kusama-0.service || sudo systemctl start kusama-0.service
        - systemctl is-active --quiet kusama-1.service || sudo systemctl start kusama-1.service
        - systemctl is-active --quiet kusama-2.service || sudo systemctl start kusama-2.service
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/internal.kusama.systems/a1/etc/systemd/system/kusama-0.service'
    target: /etc/systemd/system/kusama-0.service
    sha256: 79261139cb30a46cc538f7adb6c85825bc8ac68cba2e75e1ee671af38955c1c3
    command:
      pre:
        - systemctl is-active --quiet kusama-0.service && sudo systemctl stop kusama-0.service
      post:
        - getent passwd substrate &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group substrate
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet kusama-0.service || sudo systemctl enable kusama-0.service
        - sudo systemctl start kusama-0.service
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/internal.kusama.systems/a1/etc/systemd/system/kusama-1.service'
    target: /etc/systemd/system/kusama-1.service
    sha256: fb00d45f1516bd297deb25f31b4d0f71276ef53918a2079e55ab9fe6e22fec0e
    command:
      pre:
        - systemctl is-active --quiet kusama-1.service && sudo systemctl stop kusama-1.service
      post:
        - getent passwd substrate &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group substrate
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet kusama-1.service || sudo systemctl enable kusama-1.service
        - sudo systemctl start kusama-1.service
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/internal.kusama.systems/a1/etc/systemd/system/kusama-2.service'
    target: /etc/systemd/system/kusama-2.service
    sha256: 0c1d704902445fe54379ca4617d7397f1d26c100849fd007f363e43b280d8961
    command:
      pre:
        - systemctl is-active --quiet kusama-2.service && sudo systemctl stop kusama-2.service
      post:
        - getent passwd substrate &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group substrate
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet kusama-2.service || sudo systemctl enable kusama-2.service
        - sudo systemctl start kusama-2.service
  -
    source: 'https://gist.githubusercontent.com/grenade/ad1a4772c47a0977204edee78691fde1/raw/options-ssl-nginx.conf'
    target: /etc/letsencrypt/options-ssl-nginx.conf
    sha256: 17baec778c05571beb0cdeb0bc1c6da3596d44d1fe567e7fee0efef80a860d01
    command:
      pre:
        - test -d /etc/letsencrypt || sudo mkdir -p /etc/letsencrypt
      post:
        - sudo chmod 644 /etc/letsencrypt/options-ssl-nginx.conf
  -
    source: 'https://gist.githubusercontent.com/grenade/ad1a4772c47a0977204edee78691fde1/raw/ssl-dhparams.pem'
    target: /etc/letsencrypt/ssl-dhparams.pem
    sha256: 9ba6429597aeed2d8617a7705b56e96d044f64b07971659382e426675105654b
    command:
      pre:
        - test -d /etc/letsencrypt || sudo mkdir -p /etc/letsencrypt
      post:
        - sudo chmod 644 /etc/letsencrypt/ssl-dhparams.pem
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/status.conf'
    target: /etc/nginx/sites-available/status.conf
    sha256: c123caec7c2871afd3500875adb026cacffc16b7c7dde4375376d1b4fb3f1f14
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
  -
    source: 'https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/internal.kusama.systems/a1/etc/nginx/sites-available/substrate.conf'
    target: /etc/nginx/sites-available/substrate.conf
    sha256: d67003e54347082695bc80527411b9a00123c243ed1638f59bfd59b0ae841e2c
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/substrate.conf /etc/nginx/sites-enabled/substrate.conf
        - sudo systemctl stop nginx.service
        - sudo systemctl start nginx.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/ws.internal.kusama.systems.conf'
    target: /etc/nginx/sites-available/ws.internal.kusama.systems.conf
    sha256: fb0f5dfafcff600c53fdcee6ae644a4c34629ffd7412633565dc881f042d98f3
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.internal.kusama.systems.conf /etc/nginx/sites-enabled/ws.internal.kusama.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: 'https://gist.githubusercontent.com/grenade/8ca7512fda41fd73c9d8dbe3fe7a548e/raw/ws.archive.internal.kusama.systems.conf'
    target: /etc/nginx/sites-available/ws.archive.internal.kusama.systems.conf
    sha256: a54a9e3940d06f57b1ac39163230374fd154e2978788703542a63913e6dfbcf7
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.archive.internal.kusama.systems.conf /etc/nginx/sites-enabled/ws.archive.internal.kusama.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
