---
hostname: i1
domain: manta.systems
ip: 94.130.217.89
action: sync
launch: '2023-04-08T05:07:00Z'
provider: hetzner-robot
price:
  amount: 47.70
  currency: usd
  term: monthly
dns:
  alias:
    -
      name: i.manta.systems
      weight: 200
    -
      name: i.archive.manta.systems
      weight: 200
package:
  - certbot
  - dirmngr
  - git
  - nginx
  - sqlite3
  - unattended-upgrades
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJx8I0j6oYirfie4pAQZQB1+fWJ7w5mFZayQvLhtSV0
      users:
        - stechu
command:
  - sudo passwd -l root
  - systemctl is-active manta.service || sudo systemctl restart manta.service
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - systemctl is-active nginx-prometheus-exporter.service || sudo systemctl restart nginx-prometheus-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - '(test -s /etc/letsencrypt/renewal/$(hostname -f).conf && grep webroot_path /etc/letsencrypt/renewal/$(hostname -f).conf) || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.5.0.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.5.0.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.5.0.linux-amd64/node_exporter )
  - test -x /usr/local/bin/nginx-prometheus-exporter || ( curl -sLo /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && sudo tar xvfz /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz -C /usr/local/bin nginx-prometheus-exporter )
  - test -x /usr/bin/unzip || sudo apt-get install -y unzip
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.8.0/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
  - grep 'worker_connections 32768;' /etc/nginx/nginx.conf &> /dev/null || sudo sed -i 's/worker_connections \+[0-9]\+;/worker_connections 32768;/' /etc/nginx/nginx.conf
file:
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    target: /etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/www-data-soft-nofile.conf
    target: /etc/security/limits.d/www-data-soft-nofile.conf
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/substrate-soft-nofile.conf
    target: /etc/security/limits.d/substrate-soft-nofile.conf
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/promtail.service
    target: /etc/systemd/system/promtail.service
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/promtail/promtail.yml
    target: /etc/promtail/promtail.yml
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/prometheus-node-exporter.service
    target: /etc/systemd/system/prometheus-node-exporter.service
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/nginx-prometheus-exporter.service
    target: /etc/systemd/system/nginx-prometheus-exporter.service
    command:
      pre:
        - systemctl is-active --quiet nginx-prometheus-exporter.service && sudo systemctl stop nginx-prometheus-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now nginx-prometheus-exporter.service
  -
    source: https://github.com/Manta-Network/Manta/releases/download/v4.0.8/manta
    target: /usr/local/bin/manta
    sha256: c151e00a497df62cd54bc9fc3a83f6e531b729325deecd4d641cbc07cbf94530
    command:
      pre:
        - systemctl is-active --quiet calamari.service && sudo systemctl stop calamari.service
        - systemctl is-active --quiet manta.service && sudo systemctl stop manta.service
      post:
        - sudo chmod +x /usr/local/bin/manta
        - systemctl is-active --quiet calamari.service || sudo systemctl start calamari.service
        - systemctl is-active --quiet manta.service || sudo systemctl start manta.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/manta.systems/i1/etc/systemd/system/manta.service
    target: /etc/systemd/system/manta.service
    command:
      pre:
        - systemctl is-active --quiet manta.service && sudo systemctl stop manta.service
      post:
        - getent passwd manta &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/substrate --user-group manta
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet manta.service || sudo systemctl enable manta.service
        - sudo systemctl start manta.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/status.conf
    target: /etc/nginx/sites-available/status.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
        - sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/manta.systems/i1/etc/nginx/sites-available/manta.conf
    target: /etc/nginx/sites-available/manta.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/manta.conf /etc/nginx/sites-enabled/manta.conf
        - sudo systemctl stop nginx.service
        - sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/i.manta.systems.conf
    target: /etc/nginx/sites-available/i.manta.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/i.manta.systems.conf /etc/nginx/sites-enabled/i.manta.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/i.archive.manta.systems.conf
    target: /etc/nginx/sites-available/i.archive.manta.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/i.archive.manta.systems.conf /etc/nginx/sites-enabled/i.archive.manta.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
