---
hostname: a2
domain: calamari.seabird.systems
action: sync
provider: hetzner-robot
dns:
  alias:
    -
      name: calamari.seabird.systems
    -
      name: archive.calamari.seabird.systems
    -
      name: ws.calamari.seabird.systems
    -
      name: ws.archive.calamari.seabird.systems
package:
  - certbot
  - dirmngr
  - git
  - nginx
  - scanlogd
  - sqlite3
  - unattended-upgrades
  - unzip
user:
  -
    username: root
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBZ/7EBrBGj975hyT5sNROd9FTym7yGoiX4wUL+DcDpY
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGhEy3dlSZZtj9RI+g7Q7K5n01cvTQryCMCDpkTqfF3/
  -
    username: mobula
    authorized:
      keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJIBSdR9Wy3S4L+Zdcu8waYe5vW2VzMoi+QafgV3IIFj
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEJx8I0j6oYirfie4pAQZQB1+fWJ7w5mFZayQvLhtSV0
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILfxkCWHMdmXufF7hLHGyQdV+v64NTbEiUFDhxyi6+fX
      users:
        - dengjianping
        - stechu
        - ferrell-code
        - garandor
        - ghzlatarev
        - aye
command:
  - sudo passwd -l root
  - systemctl is-active calamari.service || sudo systemctl restart calamari.service
  - systemctl is-active manta-indexer.service || sudo systemctl manta-indexer calamari.service
  - systemctl is-active nginx.service || sudo systemctl restart nginx.service
  - systemctl is-active prometheus-node-exporter.service || sudo systemctl restart prometheus-node-exporter.service
  - systemctl is-active nginx-prometheus-exporter.service || sudo systemctl restart nginx-prometheus-exporter.service
  - timedatectl show | grep Timezone=UTC &> /dev/null || sudo timedatectl set-timezone UTC
  - '(test -s /etc/letsencrypt/renewal/$(hostname -f).conf && grep webroot_path /etc/letsencrypt/renewal/$(hostname -f).conf) || sudo certbot certonly --noninteractive --cert-name $(hostname -f) --expand --allow-subset-of-names -m ops@manta.network --agree-tos --no-eff-email --preferred-challenges http --webroot --webroot-path /var/www/html -d $(hostname -f)'
  - 'test -s /etc/letsencrypt/renewal/$(hostname -f).conf && sudo rm -f /etc/nginx/sites-enabled/default'
  - test -x /usr/local/bin/node_exporter || ( curl -sLo /tmp/node_exporter-1.3.1.linux-amd64.tar.gz https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz && sudo tar xvfz /tmp/node_exporter-1.3.1.linux-amd64.tar.gz -C /usr/local/bin --strip-components=1 node_exporter-1.3.1.linux-amd64/node_exporter )
  - test -x /usr/local/bin/nginx-prometheus-exporter || ( curl -sLo /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.11.0/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz && sudo tar xvfz /tmp/nginx-prometheus-exporter_0.11.0_linux_amd64.tar.gz -C /usr/local/bin nginx-prometheus-exporter )
  - test -x /usr/local/bin/promtail-linux-amd64 || ( curl -Lo /tmp/promtail-linux-amd64.zip https://github.com/grafana/loki/releases/download/v2.6.1/promtail-linux-amd64.zip && sudo unzip /tmp/promtail-linux-amd64.zip -d /usr/local/bin )
  - grep 'worker_connections 32768;' /etc/nginx/nginx.conf &> /dev/null || sudo sed -i 's/worker_connections \+[0-9]\+;/worker_connections 32768;/' /etc/nginx/nginx.conf
file:
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/ssh/sshd_config.d/timeout-180.conf
    target: /etc/ssh/sshd_config.d/timeout-180.conf
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    target: /etc/nginx/modules-enabled/worker_rlimit_nofile.conf
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/www-data-soft-nofile.conf
    target: /etc/security/limits.d/www-data-soft-nofile.conf
    command:
      pre:
        - ( systemctl is-active --quiet nginx.service && sudo systemctl stop nginx.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet nginx.service || sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/security/limits.d/substrate-soft-nofile.conf
    target: /etc/security/limits.d/substrate-soft-nofile.conf
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/promtail.service
    target: /etc/systemd/system/promtail.service
    command:
      pre:
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet promtail.service || sudo systemctl enable promtail.service
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/promtail/promtail.yml
    target: /etc/promtail/promtail.yml
    command:
      pre:
        - sudo mkdir -p /etc/promtail
        - ( systemctl is-active --quiet promtail.service && sudo systemctl stop promtail.service ) || true
      post:
        - sudo systemctl daemon-reload
        - systemctl is-active --quiet promtail.service || sudo systemctl start promtail.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/prometheus-node-exporter.service
    target: /etc/systemd/system/prometheus-node-exporter.service
    command:
      pre:
        - systemctl is-active --quiet prometheus-node-exporter.service && sudo systemctl stop prometheus-node-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now prometheus-node-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/nginx-prometheus-exporter.service
    target: /etc/systemd/system/nginx-prometheus-exporter.service
    command:
      pre:
        - systemctl is-active --quiet nginx-prometheus-exporter.service && sudo systemctl stop nginx-prometheus-exporter.service
      post:
        - sudo systemctl daemon-reload
        - sudo systemctl enable --now nginx-prometheus-exporter.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/status.conf
    target: /etc/nginx/sites-available/status.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/status.conf /etc/nginx/sites-enabled/status.conf
        - sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/config/calamari.seabird.systems/a2/etc/nginx/sites-available/calamari.conf
    target: /etc/nginx/sites-available/calamari.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/calamari.conf /etc/nginx/sites-enabled/substrate.conf
        - sudo systemctl stop nginx.service
        - sudo systemctl start nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/ws.calamari.seabird.systems.conf
    target: /etc/nginx/sites-available/ws.calamari.seabird.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.calamari.seabird.systems.conf /etc/nginx/sites-enabled/ws.calamari.seabird.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/ws.archive.calamari.seabird.systems.conf
    target: /etc/nginx/sites-available/ws.archive.calamari.seabird.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/ws.archive.calamari.seabird.systems.conf /etc/nginx/sites-enabled/ws.archive.calamari.seabird.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/calamari.seabird.systems.conf
    target: /etc/nginx/sites-available/calamari.seabird.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/calamari.seabird.systems.conf /etc/nginx/sites-enabled/calamari.seabird.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/nginx/sites-available/archive.calamari.seabird.systems.conf
    target: /etc/nginx/sites-available/archive.calamari.seabird.systems.conf
    command:
      pre:
        - test -d /etc/nginx/sites-available || sudo mkdir -p /etc/nginx/sites-available
        - test -d /etc/nginx/sites-enabled || sudo mkdir -p /etc/nginx/sites-enabled
      post:
        - sudo ln -sfr /etc/nginx/sites-available/archive.calamari.seabird.systems.conf /etc/nginx/sites-enabled/archive.calamari.seabird.systems.conf
        - systemctl is-active --quiet nginx.service && sudo systemctl restart nginx.service
  -
    source: https://manta-ops.s3.amazonaws.com/manta-indexer/v4.0.0/manta-indexer
    target: /usr/local/bin/manta-indexer
    sha256: c6b4afd811e363291245c26ec995a7709bdeb43732e89720527b8a3f1b58ac22
    command:
      pre:
        - test -d /usr/local/bin || sudo mkdir -p /usr/local/bin
      post:
        - sudo chmod +x /usr/local/bin/manta-indexer
        - systemctl is-active --quiet manta-indexer.service && sudo systemctl restart manta-indexer.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/manta-indexer/config.toml
    target: /etc/manta-indexer/config.toml
    command:
      pre:
        - test -d /etc/manta-indexer || sudo mkdir -p /etc/manta-indexer
      post:
        - systemctl is-active --quiet manta-indexer.service && sudo systemctl restart manta-indexer.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/manta-indexer/log.yaml
    target: /etc/manta-indexer/log.yaml
    command:
      pre:
        - test -d /etc/manta-indexer || sudo mkdir -p /etc/manta-indexer
      post:
        - systemctl is-active --quiet manta-indexer.service && sudo systemctl restart manta-indexer.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/var/lib/manta-indexer/migrations/0_schema.sql
    target: /var/lib/manta-indexer/migrations/0_schema.sql
    command:
      pre:
        - test -d /var/lib/manta-indexer/migrations || sudo mkdir -p /var/lib/manta-indexer/migrations
      post:
        - systemctl is-active --quiet manta-indexer.service && sudo systemctl restart manta-indexer.service
  -
    source: https://raw.githubusercontent.com/Manta-Network/rubberneck/main/static/etc/systemd/system/manta-indexer.service
    target: /etc/systemd/system/manta-indexer.service
    command:
      pre:
        - systemctl is-active --quiet manta-indexer.service && sudo systemctl stop manta-indexer.service
        - getent passwd manta-indexer &> /dev/null || sudo useradd --system --create-home --home-dir /var/lib/manta-indexer --user-group manta-indexer
        - test -d /var/log/manta-indexer || sudo mkdir -p /var/log/manta-indexer
        - sudo ln -sf /var/log/manta-indexer /var/lib/manta-indexer/logs
        - test -d /etc/manta-indexer || sudo mkdir -p /etc/manta-indexer
        - sudo ln -sf /etc/manta-indexer /var/lib/manta-indexer/conf
        - sudo chown -R manta-indexer:manta-indexer /var/lib/manta-indexer
        - sudo chown -R manta-indexer:manta-indexer /var/log/manta-indexer
      post:
        - sudo systemctl daemon-reload
        - systemctl is-enabled --quiet manta-indexer.service || sudo systemctl enable manta-indexer.service
        - systemctl is-active --quiet manta-indexer.service || sudo systemctl start manta-indexer.service
