---
refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%3f)} {l} {f}:{L} - {m}{n}"
  log_app:
    kind: rolling_file
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5Gb
      roller:
        kind: delete
    append: false
    path: "logs/app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%3f)} {l} {f}:{L} - {m}{n}"
  log_indexer:
    kind: rolling_file
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5Gb
      roller:
        kind: delete
    append: false
    path: "logs/indexer.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%3f)} {l} {f}:{L} - {m}{n}"
root:
  level: warn
  appenders:
    - log_app
loggers:
  indexer:
    level: debug
    appenders:
      - log_indexer
    additive: false
